/**
 * GitAntivirus - Report Generator
 * Generates comprehensive security scan reports
 */

class ReportGenerator {
  constructor() {
    this.severityOrder = {
      critical: 4,
      high: 3,
      medium: 2,
      low: 1,
      info: 0
    };
  }

  /**
   * Generate markdown report
   * @param {Array} findings - All security findings
   * @param {Object} options - Report options
   * @returns {string} Markdown report
   */
  generateMarkdown(findings, options = {}) {
    const { repoName = 'Repository', timestamp = new Date() } = options;
    
    const stats = this.calculateStats(findings);
    const sortedFindings = this.sortFindings(findings);
    const groupedFindings = this.groupBySeverity(sortedFindings);
    
    let report = this.generateHeader(repoName, timestamp);
    report += this.generateSummary(stats);
    report += this.generateExecutiveSummary(stats);
    
    // Add findings by severity
    for (const severity of ['critical', 'high', 'medium', 'low', 'info']) {
      const severityFindings = groupedFindings[severity] || [];
      if (severityFindings.length > 0) {
        report += this.generateSeveritySection(severity, severityFindings);
      }
    }
    
    report += this.generateRecommendations(findings);
    report += this.generateFooter();
    
    return report;
  }

  /**
   * Generate report header
   * @param {string} repoName - Repository name
   * @param {Date} timestamp - Scan timestamp
   * @returns {string} Header markdown
   */
  generateHeader(repoName, timestamp) {
    return `# 🛡️ GitAntivirus Security Scan Report

**Repository:** ${repoName}  
**Scan Date:** ${timestamp.toISOString()}  
**Generated by:** GitAntivirus v1.0.0

---

`;
  }

  /**
   * Generate summary section
   * @param {Object} stats - Statistics
   * @returns {string} Summary markdown
   */
  generateSummary(stats) {
    const criticalEmoji = stats.critical > 0 ? '🚨' : '✅';
    const highEmoji = stats.high > 0 ? '⚠️' : '✅';
    const mediumEmoji = stats.medium > 0 ? '⚡' : '✅';
    const lowEmoji = stats.low > 0 ? 'ℹ️' : '✅';
    
    return `## 📊 Summary

| Severity | Count | Status |
|----------|-------|--------|
| ${criticalEmoji} Critical | ${stats.critical} | ${stats.critical > 0 ? 'Action Required' : 'None Found'} |
| ${highEmoji} High | ${stats.high} | ${stats.high > 0 ? 'Action Required' : 'None Found'} |
| ${mediumEmoji} Medium | ${stats.medium} | ${stats.medium > 0 ? 'Review Recommended' : 'None Found'} |
| ${lowEmoji} Low | ${stats.low} | ${stats.low > 0 ? 'Minor Issues' : 'None Found'} |
| 📝 Info | ${stats.info} | Informational |
| **Total** | **${stats.total}** | |

`;
  }

  /**
   * Generate executive summary
   * @param {Object} stats - Statistics
   * @returns {string} Executive summary markdown
   */
  generateExecutiveSummary(stats) {
    let summary = `## 🎯 Executive Summary

`;
    
    if (stats.total === 0) {
      summary += `✅ **Great news!** No security issues were detected in this scan.

`;
      return summary;
    }
    
    if (stats.critical > 0) {
      summary += `🚨 **CRITICAL:** ${stats.critical} critical issue(s) require immediate attention. These vulnerabilities pose serious security risks and should be addressed immediately.

`;
    }
    
    if (stats.high > 0) {
      summary += `⚠️ **HIGH PRIORITY:** ${stats.high} high-severity issue(s) detected. These should be addressed as soon as possible.

`;
    }
    
    if (stats.medium > 0) {
      summary += `⚡ **MEDIUM PRIORITY:** ${stats.medium} medium-severity issue(s) found. Review and address these in your next sprint.

`;
    }
    
    if (stats.low > 0) {
      summary += `ℹ️ **LOW PRIORITY:** ${stats.low} low-severity issue(s) identified. Address these as time permits.

`;
    }
    
    if (stats.autoFixable > 0) {
      summary += `🤖 **Auto-Fix Available:** ${stats.autoFixable} issue(s) can be automatically fixed. Run \`@GitAntivirus fix\` to apply fixes.

`;
    }
    
    return summary;
  }

  /**
   * Generate severity section
   * @param {string} severity - Severity level
   * @param {Array} findings - Findings of this severity
   * @returns {string} Section markdown
   */
  generateSeveritySection(severity, findings) {
    const emoji = {
      critical: '🚨',
      high: '⚠️',
      medium: '⚡',
      low: 'ℹ️',
      info: '📝'
    };
    
    const title = severity.charAt(0).toUpperCase() + severity.slice(1);
    
    let section = `## ${emoji[severity]} ${title} Severity Issues

Found ${findings.length} ${severity} severity issue(s):

`;
    
    findings.forEach((finding, index) => {
      section += this.generateFindingDetail(finding, index + 1);
    });
    
    return section;
  }

  /**
   * Generate finding detail
   * @param {Object} finding - Finding object
   * @param {number} index - Finding number
   * @returns {string} Finding markdown
   */
  generateFindingDetail(finding, index) {
    let detail = `### ${index}. ${finding.name}

`;
    
    detail += `- **Type:** \`${finding.type}\`\n`;
    detail += `- **Severity:** ${finding.severity.toUpperCase()}\n`;
    detail += `- **File:** \`${finding.file}\`\n`;
    
    if (finding.line) {
      detail += `- **Line:** ${finding.line}\n`;
    }
    
    if (finding.package) {
      detail += `- **Package:** \`${finding.package}\`\n`;
      detail += `- **Current Version:** \`${finding.currentVersion}\`\n`;
      if (finding.fixedVersion) {
        detail += `- **Fixed Version:** \`${finding.fixedVersion}\`\n`;
      }
      if (finding.cve) {
        detail += `- **CVE:** ${finding.cve.join(', ')}\n`;
      }
    }
    
    if (finding.description) {
      detail += `\n**Description:**  \n${finding.description}\n`;
    }
    
    if (finding.code) {
      detail += `\n**Code:**\n\`\`\`javascript\n${finding.code}\n\`\`\`\n`;
    }
    
    if (finding.context) {
      detail += `\n**Context:**\n\`\`\`\n${finding.context}\n\`\`\`\n`;
    }
    
    if (finding.recommendation) {
      detail += `\n**Recommendation:**  \n${finding.recommendation}\n`;
    }
    
    if (finding.autoFixable) {
      detail += `\n✅ **Auto-fixable:** Yes\n`;
    }
    
    detail += '\n---\n\n';
    
    return detail;
  }

  /**
   * Generate recommendations section
   * @param {Array} findings - All findings
   * @returns {string} Recommendations markdown
   */
  generateRecommendations(findings) {
    if (findings.length === 0) {
      return '';
    }
    
    let section = `## 💡 Recommendations

### Immediate Actions

`;
    
    const critical = findings.filter(f => f.severity === 'critical');
    const high = findings.filter(f => f.severity === 'high');
    
    if (critical.length > 0) {
      section += '1. **Address Critical Issues Immediately**\n';
      critical.slice(0, 3).forEach(f => {
        section += `   - ${f.name} in \`${f.file}\`\n`;
      });
      section += '\n';
    }
    
    if (high.length > 0) {
      section += '2. **Fix High Priority Issues**\n';
      high.slice(0, 3).forEach(f => {
        section += `   - ${f.name} in \`${f.file}\`\n`;
      });
      section += '\n';
    }
    
    section += `### Best Practices

- 🔐 Never commit sensitive data (API keys, passwords, tokens) to version control
- 📦 Keep dependencies up to date and regularly scan for vulnerabilities
- 🔍 Use automated security scanning in your CI/CD pipeline
- ✅ Enable branch protection and require security scans before merging
- 📝 Add \`.env\`, \`*.key\`, and other sensitive files to \`.gitignore\`
- 🤖 Use environment variables for configuration and secrets

`;
    
    return section;
  }

  /**
   * Generate report footer
   * @returns {string} Footer markdown
   */
  generateFooter() {
    return `---

## 🆘 Need Help?

- 📧 Email: support@cyberai.ecosystem
- 💬 Discord: [Join our server](https://discord.gg/cyberai)
- 📖 Documentation: [GitAntivirus Docs](https://docs.gitantivirus.io)
- 🐛 Report Issues: [GitHub Issues](https://github.com/SolanaRemix/GitAntivirus/issues)

---

**Generated by GitAntivirus** - Keeping your code secure, one commit at a time.

*Made with ❤️ by the CyberAi Team*
`;
  }

  /**
   * Calculate statistics
   * @param {Array} findings - All findings
   * @returns {Object} Statistics
   */
  calculateStats(findings) {
    const stats = {
      total: findings.length,
      critical: 0,
      high: 0,
      medium: 0,
      low: 0,
      info: 0,
      autoFixable: 0,
      byType: {}
    };
    
    findings.forEach(finding => {
      const severity = finding.severity?.toLowerCase() || 'info';
      stats[severity] = (stats[severity] || 0) + 1;
      
      if (finding.autoFixable) {
        stats.autoFixable++;
      }
      
      const type = finding.type || 'unknown';
      stats.byType[type] = (stats.byType[type] || 0) + 1;
    });
    
    return stats;
  }

  /**
   * Sort findings by severity and name
   * @param {Array} findings - All findings
   * @returns {Array} Sorted findings
   */
  sortFindings(findings) {
    return [...findings].sort((a, b) => {
      const severityA = this.severityOrder[a.severity?.toLowerCase()] || 0;
      const severityB = this.severityOrder[b.severity?.toLowerCase()] || 0;
      
      if (severityA !== severityB) {
        return severityB - severityA;
      }
      
      return (a.name || '').localeCompare(b.name || '');
    });
  }

  /**
   * Group findings by severity
   * @param {Array} findings - All findings
   * @returns {Object} Grouped findings
   */
  groupBySeverity(findings) {
    const groups = {
      critical: [],
      high: [],
      medium: [],
      low: [],
      info: []
    };
    
    findings.forEach(finding => {
      const severity = finding.severity?.toLowerCase() || 'info';
      if (groups[severity]) {
        groups[severity].push(finding);
      }
    });
    
    return groups;
  }

  /**
   * Generate JSON report
   * @param {Array} findings - All findings
   * @param {Object} options - Report options
   * @returns {string} JSON report
   */
  generateJSON(findings, options = {}) {
    const stats = this.calculateStats(findings);
    
    return JSON.stringify({
      version: '1.0.0',
      timestamp: new Date().toISOString(),
      repository: options.repoName || 'Unknown',
      summary: stats,
      findings: findings
    }, null, 2);
  }
}

module.exports = ReportGenerator;
